import puppeteer from 'puppeteer-core'; import { writeFileSync } from 'node:fs';
const S = process.argv[2];
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const p = await b.newPage(); await p.setViewport({ width: 1512, height: 800, deviceScaleFactor: 2 }); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:8000/#/collection', { waitUntil: 'networkidle0' }); await p.evaluate(() => document.fonts.ready); await new Promise(r => setTimeout(r, 500));
await p.screenshot({ path: S + '/v_coll.png' });
const t = await p.$('.tl:nth-child(9)'); await t.hover(); await new Promise(r => setTimeout(r, 300)); await p.screenshot({ path: S + '/v_coll_pop.png' });
const pb = await p.$eval('#pop', e => { const r = e.getBoundingClientRect(); return [r.left, r.top, r.right, r.bottom]; }); console.log('pop box', pb.map(Math.round).join(','));
await p.goto('http://localhost:8000/#/lab/mid', { waitUntil: 'networkidle0' }); await new Promise(r => setTimeout(r, 1500));
await p.screenshot({ path: S + '/v_game.png' });
const h = await p.$('#hand .hc:nth-child(2)'); const hb = await h.boundingBox(); await p.mouse.move(hb.x + hb.width / 2, hb.y + hb.height / 2); await new Promise(r => setTimeout(r, 400));
await p.screenshot({ path: S + '/v_hover.png' });
console.log('hovered card box', JSON.stringify(await p.$eval('#hand .hc:hover .card', e => { const r = e.getBoundingClientRect(); return [r.left, r.top, r.right, r.bottom].map(Math.round); })), 'viewport 1512x800');
console.log('errors', errs.join(' | ') || 'none'); await b.close();
